Repository ShadowDuckStudio/ProjectHenchman, pull requests merged in 2024-07, with the labels that each got.

#155 Added Stun & Updated Attack To AI
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Enemies/BB_Enemy.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Enemies/BP_Enemy_Base.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Enemies/BTTask_Attack.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Enemies/BT_Enemy.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Player/EquipSystem/Equipment/BP_EquipmentHammer.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/WorldMechanics/BP_MoveableFallingRock.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/WorldMechanics/BP_RockFaller.uasset
Labels: wontfix

#181 Changed Bombs To Explode Not Puddle
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/DOT/AC_DOT_Base.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Enemies/BP_Enemy_Base.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Minion/BP_SlimeMinion.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Traps/BP_Trap_BombSpawner.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Levels/LairLevel_Blockout.umap
Labels: wontfix

#190 Reparent lava straight from lava bend. Rename Straight for spelling
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/WorldMechanics/BP_LavaVent.uasset
Labels: bug

#194 Made Player Swap To Pick When In Caves Empty Handed
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/WorldMechanics/BP_PickaxeSwapCollision.uasset
Labels: wontfix

#195 Made Wave System Manually Set
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/SpawnSystem/BI_SpawnInterface.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/SpawnSystem/BP_SpawnLocation.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/SpawnSystem/BP_SpawnManager.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/SpawnSystem/F_EnemiesPerWave.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Turrets/Projectiles/BP_ProjectileBase.uasset
Labels: wontfix

#196 Fixed Mining Mechanic Not Working
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Player/EquipSystem/AC_EquipComponent.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/ResourcesSystem/BP_ResourceBase.uasset
Labels: wontfix

#207 Added Hammer Tool & Turret Changes
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Player/EquipSystem/Equipment/BP_EquipmentHammer.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Turrets/BP_Turret_Hammer.uasset
Labels: wontfix

#214 Made Enemies Able To Drop Randomised Amounts Of Resource
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Enemies/BP_EnemySlow.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Enemies/BP_Enemy_Base.uasset
Labels: wontfix

#223 Fixed the turret
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Turrets/BP_Turret_Hammer.uasset
Labels: invalid, wontfix

#222 Increased Range To Reduce Likelyhood Of Leaving Collision
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Enemies/BP_Enemy_Base.uasset
Labels: wontfix

#225 HookedUpNodes CorrectlyToEnsureCorrectSizing
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Player/EquipSystem/AC_EquipComponent.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Player/EquipSystem/Equipment/BP_EquipmentPickaxe.uasset
Labels: wontfix

#224 AlteredLavaMeshCollisionToFixBug
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/WorldMechanics/BP_LavaVent.uasset
Labels: wontfix

#231 Removed Boulder Which Was Breaking Tutorial, Replaced With Pickaxe Co…
  SDSProjectHenchman/Content/ShadowDuckStudio/Tutorial/Map/Updated_Tutorial_Map.umap
Labels: wontfix

#230 ChangedBuildToSwapWhereTagsApply
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/BuildSystem/AC_BuildComponent.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/Traps/BP_Trap_FireTrap.uasset
  SDSProjectHenchman/Content/ShadowDuckStudio/Blueprints/WorldMechanics/BP_LavaMechanic.uasset
Labels: wontfix
